name: Build Python Flask Web App

on:
  push:
    branches: ['main']

env:
  PYTHON_VERSION: '3.13'
  ZIP_NAME: 'app_package.zip'
  APP_NAME: 'ijdemo1'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set App Insights connection string
        run: echo "APPINSIGHTS_CONNECTION_STRING=${{ secrets.APPINSIGHTS_CONNECTION_STRING }}" >> $GITHUB_ENV

# zip python application
      - name: Zip application files
        run: zip -r ${{env.ZIP_NAME}} . -x '*.git*' '__pycache__/*'

# upload zip file as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: ${{env.ZIP_NAME}}

# login to azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

# deploy to azure web app
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_NAME}}
          package: ${{env.ZIP_NAME}}